"""botcore-connectors — typed HTTP connectors for botcore."""

from botcore_connectors.audit import AuditLogEntry, AuditLogger, sanitize_args
from botcore_connectors.auth import (
    AuthConfig,
    CredentialResolver,
    DefaultCredentialResolver,
    TokenCacheEntry,
)
from botcore_connectors.base import ConnectorBase, ConnectorContext
from botcore_connectors.config import (
    KNOWN_CONNECTORS,
    AzureBlobConfig,
    AzureQueueConfig,
    ConnectorsConfig,
    EmailConfig,
    GitHubConnectorConfig,
)
from botcore_connectors.errors import (
    GITHUB_ERROR_REMAP,
    audit_write_failed,
    check_scope,
    config_missing_required,
    github_not_found,
    github_rate_limited,
    github_search_rate_limited,
    github_validation_error,
    input_too_large,
    input_validation_failed,
    invalid_repo,
    path_traversal_blocked,
    scope_violation,
)
from botcore_connectors.github import GitHubConnector
from botcore_connectors.github_commands import (
    CodeSearchResult,
    CommentResult,
    GitHubCommandSet,
    IssueResult,
    IssueSearchResult,
    PRResult,
    ReviewResult,
    create_github_commands,
    resolve_repo,
)
from botcore_connectors.plugin import ConnectorsPlugin
from botcore_connectors.validation import (
    MAX_BODY_SIZE,
    MAX_IDENTIFIER_LENGTH,
    MAX_ITEMS_DEFAULT,
    InputValidationResult,
    PaginationParams,
    check_max_body_size,
    check_max_items,
    check_max_length,
    check_no_path_traversal,
    check_owner_repo,
    check_review_event,
    validate_inputs,
)

__all__ = [
    "AuditLogEntry",
    "AuditLogger",
    "AuthConfig",
    "AzureBlobConfig",
    "AzureQueueConfig",
    "CodeSearchResult",
    "CommentResult",
    "ConnectorBase",
    "ConnectorContext",
    "ConnectorsConfig",
    "ConnectorsPlugin",
    "CredentialResolver",
    "DefaultCredentialResolver",
    "EmailConfig",
    "GITHUB_ERROR_REMAP",
    "GitHubCommandSet",
    "GitHubConnector",
    "GitHubConnectorConfig",
    "InputValidationResult",
    "IssueResult",
    "IssueSearchResult",
    "KNOWN_CONNECTORS",
    "MAX_BODY_SIZE",
    "MAX_IDENTIFIER_LENGTH",
    "MAX_ITEMS_DEFAULT",
    "PaginationParams",
    "PRResult",
    "ReviewResult",
    "TokenCacheEntry",
    "audit_write_failed",
    "check_max_body_size",
    "check_max_items",
    "check_max_length",
    "check_no_path_traversal",
    "check_owner_repo",
    "check_review_event",
    "check_scope",
    "config_missing_required",
    "create_github_commands",
    "github_not_found",
    "github_rate_limited",
    "github_search_rate_limited",
    "github_validation_error",
    "input_too_large",
    "input_validation_failed",
    "invalid_repo",
    "path_traversal_blocked",
    "resolve_repo",
    "sanitize_args",
    "scope_violation",
    "validate_inputs",
]
